### ISSUE TITLE
Properties of Resource class crash client and server

### ISSUE THREAD

**Issue by xxshady** [altmp/altv-js-module#149]
### Description of the problem

/

### Reproduction steps

Two resources.

1. Stop second resource from script or console server command
2. Get second resource instance in first resource and try to read properties of it

[resources.zip](https://github.com/altmp/altv-js-module/files/8682586/resources.zip)

### Expected behaviour

/

### Operating system

Windows 11

### Version

10.0-dev21 or 10.0-rc2

### Scope

shared

**Comment by LeonMrBonnie** [comment]
This is like the lowest of low priorities, because this is a scenario that will never ever happen for 99.9% of all servers.
No one will stop a resource at runtime without restarting it and then access the Resource instance for it, this is a edge case that is so unlikely that it's just not worth for me to spend my time on

You can fix it yourself by using the `resourceStart` and `resourceStop` event callbacks getter available for `V8Helpers::EventHandler`, to mark a resource object as invalid and delete it or something.
