### ISSUE TITLE
Slow MySQL queries

### ISSUE THREAD

**Issue by LeonMrBonnie** [altmp/altv-js-module#23]
**Describe the bug**
MySQL queries in the alt:V environment are way slower than in a normal NodeJS environment.

**To Reproduce**
Do a MySQL query and log the time it takes, you will see that a simple query takes about 100ms, while in normal NodeJS it doesn't even take a single ms.

**Expected behavior**
MySQL queries should be the same as in normal NodeJS:

**Screenshots**
N/A

**Environment:**
 - OS: Windows 10 / Ubuntu 20.04 (WSL2) (Both have the same problem)
 - alt:V server version: 2,2-rc12
 - Other installed modules: N/A
 - JS module version: 1.2-rc4

**Additional context**
This problem was described here already: https://github.com/altmp/altv-issues/issues/453

**Comment by LeonMrBonnie** [comment]
After researching this bug I have found the problem.
In `CNodeScriptRuntime::OnTick` the event loop gets updated, but this OnTick method is only called every 50ms which causes the event loop to be very slow.
There are now two options for fixing this:

1. Increase the tick count, so that it is called more often than 50ms
2. Handle updating the event loop independent from tick count

**Comment by dictateurfou** [comment]
i make a test , the time of loop is called per iResource (i think but the reference of tick path to iResource)
i just make new thread when you start resource
in CNodeScriptRuntime i add this the method is not really proper because if resource stop i d'ont destroy the thread it's just for example the timer now is 3ms not really node performance but its correct
```c++
#include <iostream>
#include <thread>
#include <chrono>


void CNodeScriptRuntime::FastTick()
{
	using namespace std::chrono_literals;
	while (true) {
		std::this_thread::sleep_for(0.05ms); //idk if really 0.05 xD
		v8::Locker locker(isolate);
		v8::Isolate::Scope isolateScope(isolate);
		v8::SealHandleScope seal(isolate);

		uv_run(uv_default_loop(), UV_RUN_NOWAIT);
		platform->DrainTasks(isolate);
	}
}
```
and on the function CNodeScriptRuntime::CNodeScriptRuntime() i add
```c++
std::thread t(&CNodeScriptRuntime::FastTick,this);
t.detach();
```

**Comment by LeonMrBonnie** [comment]
That is not a valid solution because some of the alt:V functions have to be called on server tick.
That solution will probably break some alt:V functions.

VadZz will find a solution for this issue.

**Comment by dictateurfou** [comment]
the tick alway exist but tick of tick of node overide alt tick function we have the essential and with better code of me it's possible to replace tick per owned function because we have the call when load and other and tick its called per alt and extended to iResource if you remove the tick of node alt:v tick alway active it's impossible to remove the alt tick call because he called on sdk and we juste have definition

**Comment by LeonMrBonnie** [comment]
This is fixed with the upgrade to NodeJS v14.
